// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.DAL.Models;

namespace TicketingSystem.DAL.Migrations
{
    [DbContext(typeof(TicketingSystemContext))]
    [Migration("20190822014626_addedemptype")]
    partial class addedemptype
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketingSystem.DAL.Models.Category", b =>
                {
                    b.Property<Guid>("categoryid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<Guid?>("severityid");

                    b.HasKey("categoryid");

                    b.HasIndex("severityid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.CategoryList", b =>
                {
                    b.Property<Guid>("CategoryListid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryListName");

                    b.Property<string>("ItGroup");

                    b.Property<int>("SlaResolvedTime");

                    b.Property<int>("SlaResponseTime");

                    b.Property<Guid>("categoryid");

                    b.Property<Guid>("severityid");

                    b.HasKey("CategoryListid");

                    b.HasIndex("categoryid");

                    b.HasIndex("severityid");

                    b.ToTable("CategoryLists");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactInfo");

                    b.Property<Guid>("EmployeeTypeid");

                    b.Property<string>("FirstName");

                    b.Property<string>("FormOfCommu");

                    b.Property<string>("LastName");

                    b.Property<Guid>("Officeid");

                    b.HasKey("EmployeeID");

                    b.HasIndex("EmployeeTypeid");

                    b.HasIndex("Officeid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.EmployeeType", b =>
                {
                    b.Property<Guid>("EmployeeTypeid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmployeeTypeName");

                    b.HasKey("EmployeeTypeid");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.ITGroup", b =>
                {
                    b.Property<Guid>("ITGroupid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ITGroupCode");

                    b.Property<string>("ITGroupName");

                    b.HasKey("ITGroupid");

                    b.ToTable("ITGroups");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Office", b =>
                {
                    b.Property<Guid>("Officeid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OfficeCode");

                    b.Property<string>("OfficeDesc");

                    b.HasKey("Officeid");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Severity", b =>
                {
                    b.Property<Guid>("severityid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SeverityCode");

                    b.Property<string>("SeverityDesc");

                    b.Property<string>("SeverityName");

                    b.HasKey("severityid");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Ticket", b =>
                {
                    b.Property<Guid>("Ticketid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<Guid>("CategoryListid");

                    b.Property<string>("ContactInfo");

                    b.Property<DateTime>("DateOfRequest");

                    b.Property<Guid>("EmployeeID");

                    b.Property<string>("FormOfCommu");

                    b.Property<Guid>("ITGroupid");

                    b.Property<bool>("IsOpen");

                    b.Property<bool>("IsUrgent");

                    b.Property<Guid>("Officeid");

                    b.Property<string>("RequestDesc");

                    b.Property<string>("RequestTitle");

                    b.Property<DateTime>("ResolveTime");

                    b.Property<DateTime>("ResponseTime");

                    b.Property<string>("Severity");

                    b.Property<string>("TrackingStatus");

                    b.Property<Guid?>("categoryid");

                    b.Property<Guid?>("severityid");

                    b.HasKey("Ticketid");

                    b.HasIndex("CategoryListid");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ITGroupid");

                    b.HasIndex("Officeid");

                    b.HasIndex("categoryid");

                    b.HasIndex("severityid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Category", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Severity")
                        .WithMany("Categories")
                        .HasForeignKey("severityid");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.CategoryList", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Category", "Category")
                        .WithMany("CategoryLists")
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("severityid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Employee", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.EmployeeType", "EmployeeType")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("Officeid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Ticket", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.CategoryList", "CategoryList")
                        .WithMany()
                        .HasForeignKey("CategoryListid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.ITGroup", "ITGroup")
                        .WithMany("Tickets")
                        .HasForeignKey("ITGroupid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Office", "Office")
                        .WithMany("Tickets")
                        .HasForeignKey("Officeid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Category")
                        .WithMany("Tickets")
                        .HasForeignKey("categoryid");

                    b.HasOne("TicketingSystem.DAL.Models.Severity")
                        .WithMany("Tickets")
                        .HasForeignKey("severityid");
                });
#pragma warning restore 612, 618
        }
    }
}
