// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.DAL.Models;

namespace TicketingSystem.DAL.Migrations
{
    [DbContext(typeof(TicketingSystemContext))]
    [Migration("20190819031136_addedGroupEmployee")]
    partial class addedGroupEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketingSystem.DAL.Models.Category", b =>
                {
                    b.Property<Guid>("categoryid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<Guid?>("categoryid1");

                    b.Property<Guid?>("severityid");

                    b.HasKey("categoryid");

                    b.HasIndex("categoryid1");

                    b.HasIndex("severityid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.CategoryList", b =>
                {
                    b.Property<Guid>("CategoryListid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryListName");

                    b.Property<string>("ItGroup");

                    b.Property<int>("SlaResolvedTime");

                    b.Property<int>("SlaResponseTime");

                    b.Property<Guid>("categoryid");

                    b.Property<Guid>("severityid");

                    b.HasKey("CategoryListid");

                    b.HasIndex("categoryid");

                    b.HasIndex("severityid");

                    b.ToTable("CategoryLists");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<Guid>("Officeid");

                    b.HasKey("EmployeeID");

                    b.HasIndex("Officeid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.GroupEmployee", b =>
                {
                    b.Property<Guid>("GroupEmployeeid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmployeeFullName");

                    b.Property<Guid>("EmployeeID");

                    b.Property<Guid>("ITGroupMemberid");

                    b.HasKey("GroupEmployeeid");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ITGroupMemberid");

                    b.ToTable("GroupEmployees");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.ITGroup", b =>
                {
                    b.Property<Guid>("ITGroupid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ITGroupCode");

                    b.Property<string>("ITGroupName");

                    b.HasKey("ITGroupid");

                    b.ToTable("ITGroups");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.ITGroupMember", b =>
                {
                    b.Property<Guid>("ITGroupMemberid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ITGroupid");

                    b.HasKey("ITGroupMemberid");

                    b.HasIndex("ITGroupid");

                    b.ToTable("ITGroupMembers");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Office", b =>
                {
                    b.Property<Guid>("Officeid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OfficeCode");

                    b.Property<string>("OfficeDesc");

                    b.HasKey("Officeid");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Severity", b =>
                {
                    b.Property<Guid>("severityid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SeverityCode");

                    b.Property<string>("SeverityDesc");

                    b.Property<string>("SeverityName");

                    b.HasKey("severityid");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Ticket", b =>
                {
                    b.Property<Guid>("Ticketid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AssistByid");

                    b.Property<Guid>("Categoryid");

                    b.Property<string>("ContactInfo");

                    b.Property<DateTime>("DateOfRequest");

                    b.Property<string>("FormOfCommu");

                    b.Property<bool>("IsOpen");

                    b.Property<bool>("IsUrgent");

                    b.Property<Guid>("ItGroupid");

                    b.Property<Guid>("Officeid");

                    b.Property<string>("RequestDesc");

                    b.Property<string>("RequestTitle");

                    b.Property<Guid>("RequestedBy");

                    b.Property<TimeSpan>("ResolveTime");

                    b.Property<TimeSpan>("ResponseTime");

                    b.Property<Guid>("Severityid");

                    b.Property<string>("TrackingSatus");

                    b.HasKey("Ticketid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Category", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Category")
                        .WithMany("Categories")
                        .HasForeignKey("categoryid1");

                    b.HasOne("TicketingSystem.DAL.Models.Severity")
                        .WithMany("Categories")
                        .HasForeignKey("severityid");
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.CategoryList", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.Severity", "Severity")
                        .WithMany()
                        .HasForeignKey("severityid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.Employee", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("Officeid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.GroupEmployee", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.Employee", "Employee")
                        .WithMany("GroupEmployees")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TicketingSystem.DAL.Models.ITGroupMember", "ITGroupMember")
                        .WithMany("GroupEmployees")
                        .HasForeignKey("ITGroupMemberid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TicketingSystem.DAL.Models.ITGroupMember", b =>
                {
                    b.HasOne("TicketingSystem.DAL.Models.ITGroup", "ITGroup")
                        .WithMany()
                        .HasForeignKey("ITGroupid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
